disabled_rules: # rule identifiers to exclude from running
  - identifier_name
  - type_name
  - force_cast
  - cyclomatic_complexity
  - todo
# configurable rules can be customized from this configuration file
# binary rules can set their severity level
type_body_length:
  - 1500 # warning
  - 2000 # error
file_length:
  - 1500 # warning
  - 3000 # error
function_body_length:
  - 80   # warning
  - 200  # error
line_length:
  - 400  # warning
  - 1000 # error
large_tuple:
  - 3    # warning
  - 6    # error