name: WebAssembly build
on: [push, pull_request]
jobs:
  build:
    name: BezierKit WASM support
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: swift-actions/setup-swift@v3
      with:
        swift-version: main-snapshot-2026-06-24
        skip-verify-signature: true

    - name: Install WebAssembly SDK
      run: swift sdk install --checksum b8e808d6c1b83636c68668eea27f504ac07973f0f8c68d0d053d11ef4eb96a44 https://github.com/swiftwasm/swift/releases/download/swift-wasm-DEVELOPMENT-SNAPSHOT-2026-06-24-a/swift-wasm-DEVELOPMENT-SNAPSHOT-2026-06-24-a-wasm32-unknown-wasip1-threads.artifactbundle.zip

    - name: Build
      run: swift build --swift-sdk DEVELOPMENT-SNAPSHOT-2026-06-24-a-wasm32-unknown-wasip1-threads
