name: WebAssembly build
on: [push, pull_request]
jobs:
  test:
    name: BezierKit WASM support
    runs-on: ubuntu-latest
    container: ghcr.io/swiftwasm/carton:0.16.0

    steps:
    - uses: actions/checkout@v2
    
    - name: Build
      run: $(find /root/.carton/sdk -path '*/usr/bin/swift' -type f | head -n 1) build --triple wasm32-unknown-wasi
