name: WebAssembly build
on: [push, pull_request]
jobs:
  test:
    name: BezierKit WASM support
    runs-on: ubuntu-latest
    container: ghcr.io/swiftwasm/carton:0.16.0

    steps:
    - uses: actions/checkout@v2
    
    - name: Build
      run: /root/.carton/sdk/$(carton sdk local)/usr/bin/swift build --triple wasm32-unknown-wasi
